version: '3.8'

services:
  app:
    build: .
    container_name: todo_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=sqlite:///./todo.db
    networks:
      - todo_network
    depends_on:
      - test

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_test
    volumes:
      - .:/app
    command: pytest -v
    environment:
      - DATABASE_URL=sqlite:///./test.db
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge